CREATE DATABASE BASEMARCO
USE BASEMARCO

CREATE TABLE FARMACEUTICO(
ID_FAR VARCHAR(15),
APAT_FAR VARCHAR(20),
AMAT_FAR VARCHAR(20),
NOM_FAR VARCHAR(30),
NEXT_FAR INT,
CP_FAR INT,
CEDULA_FAR INT,
CORREO_FAR VARCHAR(25),
ID_CALLE2 VARCHAR(15),
ID_COL2 VARCHAR(15),
ID_ALCA2 VARCHAR(15),
ID_CIU2 VARCHAR(15),
ID_HOR2 VARCHAR(15),
constraint PK_FAR primary key (ID_FAR))

insert into FARMACEUTICO values('1','Arenas',		'Sosa',		'Luis Alberto',	155,	'00810','9877985','arenas@gmail.com',			'5','4','6','1','1')
insert into FARMACEUTICO values('2','Castillejos',	'Peralta',	'Nancy',		201,	'01000','1357945','castillo@hotmail.com',		'6','7','5','10','2')
insert into FARMACEUTICO values('3','Córdova',		'Díaz',		'Gustavo',		48,		'10100','7194573','cordova@yahoo.com',			'4','6','3','2','3')
insert into FARMACEUTICO values('4','Corona',		'Gutiérrez','Omar',			295,	'01020','0116845','corona@gmail.com',			'1','3','8','9','4')
insert into FARMACEUTICO values('5','Delgado',		'Díaz',		'Rene',			44,		'10255','3633584','delgadiz@outlook',			'2','2','9','3','2')
insert into FARMACEUTICO values('6','Díaz',			'Velázquez','Francisco',	301,	'21255','3344714','diazfranc@gmail.com',		'7','8','4','8','3')
insert into FARMACEUTICO values('7','Enciso',		'Tabaco',	'Pedro',		1,		'31081','1154741','encisotab@gmail.com',		'3','5','10','4','1')
insert into FARMACEUTICO values('8','Esquivel',		'Mundo',	'Griselda',		23,		'01070','0100154','esquivm@hotmail.com',		'8','9','2','7','2')
insert into FARMACEUTICO values('9','Fernández',	'Estrada',	'Virginia',		89,		'01080','1818741','fernezest@yahoo.com',		'10','10','1','5','3')
insert into FARMACEUTICO values('10','Ferreira',	'García',	'Miguel',		555,	'01090','9868964','ferrr318@hotmal.com',		'9','1','7','6','4')

select *
from FARMACEUTICO


create TABLE PUESTO(
ID_PUESTO VARCHAR(15),
NOM_PUESTO VARCHAR(25),
constraint PK_PUES primary key (ID_PUESTO))

INSERT INTO PUESTO VALUES('1','CEO')
INSERT INTO PUESTO VALUES('2','Gerente Financiero')
INSERT INTO PUESTO VALUES('3','Gerente Comercial')
INSERT INTO PUESTO VALUES('4','Gerente de Marketing')
INSERT INTO PUESTO VALUES('5','Gerente Administrativo')
INSERT INTO PUESTO VALUES('6','Gerente de Marketing')
INSERT INTO PUESTO VALUES('7','Recursos Humanos')
INSERT INTO PUESTO VALUES('8','Encargado de ventas')
INSERT INTO PUESTO VALUES('9','Cajero')
INSERT INTO PUESTO VALUES('10','Ingeniero ISC')


﻿
alter login sa enable
alter login sa with password = 'sasa'

---- GENERAR CLAVE AUTOMATICA, EXTANDAR DE CLAVE PRIMARIA DE 15


/*PROCEDIMIENTOS DE CONSULTAS SIMPLES: 
	1.CONSULTAS SIMPLES
	2.VISUALIZAR EL NOMBRE COMPLETO DEL FARMACEUTICO, CON DIRECCION COMPLETA, CÉDULA, CORREO Y HORARIO.
	3.VISUALIZAR EL NOMBRE COMPLETO DEL EMPLEADO, CON DIRECCION COMPLETA, PUESTO Y HORARIO*/

-------------------------------------------------------------------------------
------------------------------ CONSULTAS SIMPLES ------------------------------
-------------------------------------------------------------------------------

---- EMPLEADO (BRIAN)
CREATE PROCEDURE CONSEMPLEADO 
AS BEGIN
	SELECT* 
	FROM [DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO
END    

GO
---- PRESENTACION (BRIAN)
CREATE PROCEDURE CONSPRESENTACION 
AS BEGIN
	SELECT* 
	FROM [DESKTOP-IUOOUHP].BASEBRIAN.DBO.PRESENTACION
END   
GO
---- EMPTIPO (ULISES)
CREATE PROCEDURE CONSEMPTIPO
AS BEGIN
	SELECT* 
	FROM [DESKTOP-CJ3JHQ2].BASEULI.DBO.EMPTIPO
END   
GO
---- CALLE (ULISES)
CREATE PROCEDURE CONSCALLE
AS BEGIN
	SELECT* 
	FROM [DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE
END   
GO
---- HORARIO (ULISES)
CREATE PROCEDURE CONSHORARIO
AS BEGIN
	SELECT* 
	FROM [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO
END   
GO
---- CIUDAD (KEVIN / VICKY:)
CREATE PROCEDURE CONSCIUDAD
AS BEGIN
	SELECT* 
	FROM  [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD
END   
GO
---- COLONIA (KEVIN / VICKY:)
CREATE PROCEDURE CONSCOLONIA
AS BEGIN
	SELECT* 
	FROM [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA
END   
GO
---- MEDMONO (KEVIN / VICKY:)
CREATE PROCEDURE CONSMEDMONO
AS BEGIN
	SELECT* 
	FROM [LAPTOP-61QAQSQG].BASEKEVS.DBO.MEDMONO
END   
GO
---- FARMEDPREUN (JORGE)
CREATE PROCEDURE CONSFARMEDPREUN
AS BEGIN
	SELECT* 
	FROM [USER-PC].BASEJORGE.DBO.FARMEDPREUN
END   
GO
---- FARMTIPO (JORGE)
CREATE PROCEDURE CONSFARMTIPO
AS BEGIN
	SELECT* 
	FROM [USER-PC].BASEJORGE.DBO.FARMTIPO
END   
GO
---- ACCIONTERAP (GENARO / VICKY:)
CREATE PROCEDURE CONSACCIONTERAP
AS BEGIN
	SELECT* 
	FROM [DESKTOP-DG326LV].BASEGENARO.DBO.ACCIONTERAP
END   
GO
---- TIPOTEL (GENARO / VICKY:)
CREATE PROCEDURE CONSTIPOTELF
AS BEGIN
	SELECT* 
	FROM [DESKTOP-DG326LV].BASEGENARO.DBO.TIPOTELF
END   
GO
---- LABORATORIO (GENARO / VICKY:)
CREATE PROCEDURE CONSLABORATORIO
AS BEGIN
	SELECT* 
	FROM [DESKTOP-DG326LV].BASEGENARO.DBO.LABORATORIO
END   
GO
---- FARMACIA (YAIR)
CREATE PROCEDURE CONSFARMACIA
AS BEGIN
	SELECT* 
	FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA
END   
GO

---- UNIDADMEDIDA (YAIR)
CREATE PROCEDURE CONSUNIDADMEDIDA
AS BEGIN
	SELECT* 
	FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.UNIDADMEDIDA
END   
GO
---- MONODROGA (YAIR)
CREATE PROCEDURE CONSMONODROGA
AS BEGIN
	SELECT* 
	FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.MONODROGA
END   
GO
---- MEDICAMENTO (MAURICIO)
CREATE PROCEDURE CONSMEDICAMENTO
AS BEGIN
	SELECT* 
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO
END   
GO
---- ALCALDIA (MAURICIO)
CREATE PROCEDURE CONSALCALDIA
AS BEGIN
	SELECT* 
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA
END   
GO
---- MEDACC (MAURICIO)
CREATE PROCEDURE CONSMEDACC
AS BEGIN
	SELECT* 
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDACC
END   
GO
---- FARMACEUTICO (MARCO)
CREATE PROCEDURE CONSFARMACEUTICO 
AS BEGIN
	SELECT* 
	FROM [DESKTOP-CGC0VV9].BASEMARCO.DBO.FARMACEUTICO
END   
GO
---- PUESTO (MARCO)
CREATE PROCEDURE CONSPUESTO
AS BEGIN
	SELECT* 
	FROM [DESKTOP-CGC0VV9].BASEMARCO.DBO.PUESTO
END  

-------------------------------
EXEC CONSEMPLEADO
EXEC CONSPRESENTACION
EXEC CONSCALLE
EXEC CONSHORARIO
EXEC CONSCIUDAD
EXEC CONSCOLONIA
EXEC CONSMEDMONO
EXEC CONSFARMEDPREUN
EXEC CONSFARMTIPO
EXEC CONSACCIONTERAP
EXEC CONSTIPOTELF
EXEC CONSLABORATORIO
EXEC CONSFARMACIA
EXEC CONSUNIDADMEDIDA
EXEC CONSMONODROGA
EXEC CONSMEDICAMENTO
EXEC CONSALCALDIA
EXEC CONSMEDACC
EXEC CONSFARMACEUTICO
EXEC CONSPUESTO
EXEC CONSEMPTIPO

---------------------------------------------------------------------------------
------------------------------ CONSULTAS COMPLEJAS ------------------------------
---------------------------------------------------------------------------------

---- 1.VISUALIZAR EL NOMBRE COMPLETO DEL FARMACEUTICO, CON DIRECCION COMPLETA, CÉDULA, CORREO Y HORARIO. SI
CREATE PROCEDURE CONFD
AS BEGIN
	SELECT APAT_FAR, AMAT_FAR, NOM_FAR, NOM_CALLE, NOM_COL, NOM_ALCA, NOM_CIU, NEXT_FAR, CEDULA_FAR, CORREO_FAR, TURNO
	FROM [DESKTOP-CGC0VV9].BASEMARCO.DBO.FARMACEUTICO
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE ON ID_CALLE2=ID_CALLE 
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA ON ID_COL2=ID_COL
	INNER JOIN [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA ON ID_ALCA2=ID_ALCA
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD ON ID_CIU2=ID_CIU
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO ON ID_HOR2=ID_HOR
END   
GO
-- 2. VISUALIZAR EL NOMBRE COMPLETO DEL EMPLEADO CON SU DIRECCION COMPLETA, PUESTO Y HORARIO
CREATE PROCEDURE CONC2
AS
BEGIN
SELECT  APAT_EMP,AMAT_EMP,NOM_EMP,NOM_CALLE,NOM_COL,NOM_ALCA,NOM_CIU,NOM_PUESTO,TURNO
FROM [DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO
INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE ON ID_CALLE1=ID_CALLE
INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA ON ID_COL1=ID_COL 
INNER JOIN [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA ON ID_ALCA1=ID_ALCA 
INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD ON ID_CIU1=ID_CIU 
INNER JOIN [DESKTOP-CGC0VV9].BASEMARCO.DBO.PUESTO ON ID_PUESTO1=ID_PUESTO
INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO ON ID_HOR1=ID_HOR 
END  
GO

--3.- VISUALIZAR EL NOMBRE DE LA FARMACIA, DIRECCION, TIPO TELEFONO, NUMERO TELEFONO. SI
CREATE PROCEDURE CONC3
AS
BEGIN
SELECT  NOM_FARMACIA, DIREC_FARMACIA, NOM_TIPOTELF, TELEFONO2
FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA 
INNER JOIN [USER-PC].BASEJORGE.DBO.FARMTIPO ON ID_FARMACIA1=ID_FARMACIA
INNER JOIN [DESKTOP-DG326LV].BASEGENARO.DBO.TIPOTELF ON ID_TIPOTELF2=ID_TIPOTELF 
END   
GO
--4.- VISUALIZAR EL NOMBRE COMPLETO DEL EMPLEADO, TIPO DE TELEFONO, Y NUM DE TEL. SI
CREATE PROCEDURE CONC4
AS
BEGIN
SELECT APAT_EMP,AMAT_EMP,NOM_EMP,NOM_TIPOTELF,TELEFONO1
FROM [DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO
INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.EMPTIPO ON ID_EMP1=ID_EMP
INNER JOIN [DESKTOP-DG326LV].BASEGENARO.DBO.TIPOTELF ON ID_TIPOTELF1=ID_TIPOTELF
END   
GO

--5.- VISUALIZAR EL NOMBRE COMPLETO DEL FARMACEUTICO, NOMBRE DE LA FARMACIA, DIRECCION QUE TIENE ASIGNADA.  SI
CREATE PROCEDURE CONC5
AS
BEGIN
SELECT APAT_FAR,AMAT_FAR,NOM_FAR,NOM_FARMACIA,NOM_CALLE,NOM_COL,NOM_ALCA,NOM_CIU,NEXT_FAR, CEDULA_FAR, CORREO_FAR,TURNO
FROM [DESKTOP-CGC0VV9].BASEMARCO.DBO.FARMACEUTICO
INNER JOIN [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA ON ID_FAR=ID_FAR1 
INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO ON ID_HOR=ID_HOR2
INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE ON ID_CALLE2=ID_CALLE
INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA ON ID_COL2=ID_COL 
INNER JOIN [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA ON ID_ALCA2=ID_ALCA 
INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD ON ID_CIU2=ID_CIU 
END   
GO
--6.- VISUALIZAR EL NOMBRE DEL MEDICAMENTO, NOMBRE DE MONODROGAS. SI
CREATE PROCEDURE CONC6
AS
BEGIN
SELECT NOM_MED,NOM_MONO
FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO 
INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.MEDMONO ON ID_MED=ID_MED2 
INNER JOIN [LAPTOP-IM7I95NH].BASEYAIR.DBO.MONODROGA ON ID_MONO=ID_MONO1 
END   
GO

--7.- VISUALIZAR NOMBRE DEL MEDICAMENTO, NOMBRE DE LABORATORIO, NOMBRE DE ACCION TERAPEUTICA. SI
CREATE PROCEDURE CONC7
AS
BEGIN
SELECT NOM_MED,NOM_LAB,NOM_ACCT
FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO 
INNER JOIN [DESKTOP-DG326LV].BASEGENARO.DBO.LABORATORIO ON ID_LAB=ID_LAB1
INNER JOIN [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDACC ON ID_MED=ID_MED3 
INNER JOIN [DESKTOP-DG326LV].BASEGENARO.DBO.ACCIONTERAP ON ID_ACCT=ID_ACCT1
END   
GO
--8.- VISUALIZAR EL NOMBRE DEL MEDICAMENTO, PRESENTACION, UNIDAD DE MEDIDA, FARMACIA QUE LO TIENE, FOLIO, PRECIO Y STOCK. X
CREATE PROCEDURE CONC8
AS
BEGIN
SELECT NOM_MED,TIPO_PRES,CANT_UM,NOM_FARMACIA,FOLIO,PRECIO,STOCK
FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO 
INNER JOIN [USER-PC].BASEJORGE.DBO.FARMEDPREUN ON ID_MED=ID_MED1 
INNER JOIN [DESKTOP-IUOOUHP].BASEBRIAN.DBO.PRESENTACION ON ID_PRES=ID_PRES1
INNER JOIN [LAPTOP-IM7I95NH].BASEYAIR.DBO.UNIDADMEDIDA ON ID_UM=ID_UM1
INNER JOIN [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA ON ID_FARMACIA=ID_FARMACIA2
END   

---- CONSULTAS COMPLEJAS
EXEC CONFD
EXEC CONC2
EXEC CONC3
EXEC CONC4
EXEC CONC5
EXEC CONC6
EXEC CONC7
EXEC CONC8


---------------------------------------------------------------------------------
------------------------------ PROCEDIMIENTOS BÚSQUEDAS COMPLEJAS ---------------
---------------------------------------------------------------------------------
EXEC CONCVICKY
EXEC CONCMARCO
EXEC CONCYAIR
EXEC CONCJORGE
EXEC CONCGENARO
EXEC CONCKEVIN
EXEC CONCMAURICIO

/***************/
--1.--
CREATE PROCEDURE BUS11
@CL VARCHAR(15)
AS 
BEGIN
	SELECT ID_FAR,APAT_FAR,AMAT_FAR,NOM_FAR,NOM_CALLE,NOM_COL,NOM_ALCA,NOM_CIU,NEXT_FAR, CEDULA_FAR, CORREO_FAR,TURNO
	FROM [DESKTOP-CGC0VV9].BASEMARCO.DBO.FARMACEUTICO
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE ON ID_CALLE2=ID_CALLE
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA ON ID_COL2=ID_COL 
	INNER JOIN [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA ON ID_ALCA2=ID_ALCA 
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD ON ID_CIU2=ID_CIU 
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO ON ID_HOR2=ID_HOR
	WHERE ID_FAR LIKE @CL+'%'  
END   
GO

create PROCEDURE BUS12
@CL VARCHAR(30)
AS 
BEGIN
	SELECT APAT_FAR,AMAT_FAR,NOM_FAR,NOM_CALLE,NOM_COL,NOM_ALCA,NOM_CIU,NEXT_FAR, CEDULA_FAR, CORREO_FAR,TURNO
	FROM [DESKTOP-CGC0VV9].BASEMARCO.DBO.FARMACEUTICO
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE ON ID_CALLE2=ID_CALLE
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA ON ID_COL2=ID_COL 
	INNER JOIN [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA ON ID_ALCA2=ID_ALCA 
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD ON ID_CIU2=ID_CIU 
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO ON ID_HOR2=ID_HOR
	WHERE NOM_FAR LIKE @CL+'%'
END   
GO


CREATE PROCEDURE BUS13
@CL VARCHAR(50)
AS 
BEGIN
	SELECT APAT_FAR,AMAT_FAR,NOM_FAR,NOM_CALLE,NOM_COL,NOM_ALCA,NOM_CIU,NEXT_FAR, CEDULA_FAR, CORREO_FAR,TURNO
	FROM [DESKTOP-CGC0VV9].BASEMARCO.DBO.FARMACEUTICO
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE ON ID_CALLE2=ID_CALLE
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA ON ID_COL2=ID_COL 
	INNER JOIN [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA ON ID_ALCA2=ID_ALCA 
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD ON ID_CIU2=ID_CIU 
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO ON ID_HOR2=ID_HOR
	WHERE TURNO LIKE @CL+'%'
END   
GO

--2.-
CREATE procedure BUS21 
@CL VARCHAR(15)
AS
BEGIN
	SELECT  APAT_EMP,AMAT_EMP,NOM_EMP,NOM_CALLE,NOM_COL,NOM_ALCA,NOM_CIU,NOM_PUESTO,TURNO
	FROM [DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE ON ID_CALLE1=ID_CALLE
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA ON ID_COL1=ID_COL 
	INNER JOIN [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA ON ID_ALCA1=ID_ALCA 
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD ON ID_CIU1=ID_CIU 
	INNER JOIN [DESKTOP-CGC0VV9].BASEMARCO.DBO.PUESTO ON ID_PUESTO1=ID_PUESTO
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO ON ID_HOR1=ID_HOR 
	WHERE ID_EMP LIKE @CL+'%'
END   

GO

create procedure BUS22 
@CL VARCHAR(50)
AS
BEGIN
	SELECT  APAT_EMP,AMAT_EMP,NOM_EMP,NOM_CALLE,NOM_COL,NOM_ALCA,NOM_CIU,NOM_PUESTO,TURNO
	FROM [DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE ON ID_CALLE1=ID_CALLE
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA ON ID_COL1=ID_COL 
	INNER JOIN [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA ON ID_ALCA1=ID_ALCA 
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD ON ID_CIU1=ID_CIU 
	INNER JOIN [DESKTOP-CGC0VV9].BASEMARCO.DBO.PUESTO ON ID_PUESTO1=ID_PUESTO
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO ON ID_HOR1=ID_HOR 
	WHERE NOM_EMP LIKE @CL+'%'
END   

GO

create procedure BUS23 
@CL VARCHAR(25)
AS
BEGIN
	SELECT  APAT_EMP,AMAT_EMP,NOM_EMP,NOM_CALLE,NOM_COL,NOM_ALCA,NOM_CIU,NOM_PUESTO,TURNO
	FROM [DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE ON ID_CALLE1=ID_CALLE
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA ON ID_COL1=ID_COL 
	INNER JOIN [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA ON ID_ALCA1=ID_ALCA 
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD ON ID_CIU1=ID_CIU 
	INNER JOIN [DESKTOP-CGC0VV9].BASEMARCO.DBO.PUESTO ON ID_PUESTO1=ID_PUESTO
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO ON ID_HOR1=ID_HOR 
	WHERE NOM_PUESTO LIKE @CL+'%'
END   

GO

create procedure BUS24 
@CL VARCHAR(50)
AS
BEGIN
	SELECT  APAT_EMP,AMAT_EMP,NOM_EMP,NOM_CALLE,NOM_COL,NOM_ALCA,NOM_CIU,NOM_PUESTO,TURNO
	FROM [DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE ON ID_CALLE1=ID_CALLE
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA ON ID_COL1=ID_COL 
	INNER JOIN [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA ON ID_ALCA1=ID_ALCA 
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD ON ID_CIU1=ID_CIU 
	INNER JOIN [DESKTOP-CGC0VV9].BASEMARCO.DBO.PUESTO ON ID_PUESTO1=ID_PUESTO
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO ON ID_HOR1=ID_HOR 
	WHERE TURNO LIKE @CL+'%'
END   

GO

--3.- 
CREATE PROCEDURE BUS31
@CL VARCHAR(100)
AS
BEGIN
	SELECT  NOM_FARMACIA, DIREC_FARMACIA, NOM_TIPOTELF, TELEFONO2
	FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA 
	INNER JOIN [USER-PC].BASEJORGE.DBO.FARMTIPO ON ID_FARMACIA1=ID_FARMACIA
	INNER JOIN [DESKTOP-DG326LV].BASEGENARO.DBO.TIPOTELF ON ID_TIPOTELF2=ID_TIPOTELF 
	WHERE NOM_FARMACIA LIKE @CL+'%'
END   
GO

CREATE PROCEDURE BUS32
@CL VARCHAR(15)
AS
BEGIN
	SELECT  NOM_FARMACIA, DIREC_FARMACIA, NOM_TIPOTELF, TELEFONO2
	FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA 
	INNER JOIN [USER-PC].BASEJORGE.DBO.FARMTIPO ON ID_FARMACIA1=ID_FARMACIA
	INNER JOIN [DESKTOP-DG326LV].BASEGENARO.DBO.TIPOTELF ON ID_TIPOTELF2=ID_TIPOTELF 
	WHERE NOM_TIPOTELF LIKE @CL+'%'
END   
GO


--4.-
CREATE PROCEDURE BUS41
@CL VARCHAR(50)
AS
BEGIN
	SELECT  APAT_EMP,AMAT_EMP,NOM_EMP,NOM_TIPOTELF,TELEFONO1
	FROM [DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.EMPTIPO ON ID_EMP=ID_EMP1 
	INNER JOIN [DESKTOP-DG326LV].BASEGENARO.DBO.TIPOTELF ON ID_TIPOTELF=ID_TIPOTELF1 
	WHERE NOM_EMP LIKE @CL+'%'
END   
GO

CREATE PROCEDURE BUS42
@CL VARCHAR(15)
AS
BEGIN
	SELECT APAT_EMP,AMAT_EMP,NOM_EMP,NOM_TIPOTELF,TELEFONO1
	FROM [DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.EMPTIPO ON ID_EMP=ID_EMP1 
	INNER JOIN [DESKTOP-DG326LV].BASEGENARO.DBO.TIPOTELF ON ID_TIPOTELF=ID_TIPOTELF1 
	WHERE NOM_TIPOTELF LIKE @CL+'%'
END   
GO

--5.-
CREATE PROCEDURE BUS51
@CL VARCHAR(30)
AS
BEGIN
	SELECT APAT_FAR,AMAT_FAR,NOM_FAR,NOM_FARMACIA,NOM_CALLE,NOM_COL,NOM_ALCA,NOM_CIU,NEXT_FAR, CEDULA_FAR, CORREO_FAR,TURNO
	FROM [DESKTOP-CGC0VV9].BASEMARCO.DBO.FARMACEUTICO
	INNER JOIN [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA ON ID_FAR=ID_FAR1 
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO ON ID_HOR=ID_HOR2
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE ON ID_CALLE2=ID_CALLE
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA ON ID_COL2=ID_COL 
	INNER JOIN [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA ON ID_ALCA2=ID_ALCA 
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD ON ID_CIU2=ID_CIU 
	WHERE NOM_FAR LIKE @CL+'%'
END   
GO

CREATE PROCEDURE BUS52
@CL VARCHAR(15)
AS
BEGIN
	SELECT APAT_FAR,AMAT_FAR,NOM_FAR,NOM_FARMACIA,NOM_CALLE,NOM_COL,NOM_ALCA,NOM_CIU,NEXT_FAR, CEDULA_FAR, CORREO_FAR,TURNO
	FROM [DESKTOP-CGC0VV9].BASEMARCO.DBO.FARMACEUTICO
	INNER JOIN [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA ON ID_FAR=ID_FAR1 
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO ON ID_HOR=ID_HOR2
	INNER JOIN [DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE ON ID_CALLE2=ID_CALLE
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA ON ID_COL2=ID_COL 
	INNER JOIN [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA ON ID_ALCA2=ID_ALCA 
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD ON ID_CIU2=ID_CIU 
	WHERE NOM_FARMACIA LIKE @CL+'%'
END   
GO


--6.-
CREATE PROCEDURE BUS61
@CL VARCHAR(30)
AS
BEGIN
	SELECT NOM_MED,NOM_MONO
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO 
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.MEDMONO ON ID_MED=ID_MED2 
	INNER JOIN [LAPTOP-IM7I95NH].BASEYAIR.DBO.MONODROGA ON ID_MONO=ID_MONO1 
	WHERE NOM_MED LIKE @CL+'%'
END   
GO

CREATE PROCEDURE BUS62
@CL VARCHAR(30)
AS
BEGIN
	SELECT NOM_MED,NOM_MONO
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO 
	INNER JOIN [LAPTOP-61QAQSQG].BASEKEVS.DBO.MEDMONO ON ID_MED=ID_MED2 
	INNER JOIN [LAPTOP-IM7I95NH].BASEYAIR.DBO.MONODROGA ON ID_MONO=ID_MONO1 
	WHERE NOM_MONO LIKE @CL+'%'
END   
GO


--7.-
CREATE PROCEDURE BUS71
@CL VARCHAR(30)
AS
BEGIN
	SELECT NOM_MED,NOM_LAB,NOM_ACCT
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO 
	INNER JOIN [DESKTOP-DG326LV].BASEGENARO.DBO.LABORATORIO ON ID_LAB=ID_LAB1
	INNER JOIN [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDACC ON ID_MED=ID_MED3 
	INNER JOIN [DESKTOP-DG326LV].BASEGENARO.DBO.ACCIONTERAP ON ID_ACCT=ID_ACCT1
	WHERE NOM_MED LIKE @CL+'%'
END   
GO

CREATE PROCEDURE BUS72
@CL VARCHAR(30)
AS
BEGIN
	SELECT NOM_MED,NOM_LAB,NOM_ACCT
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO 
	INNER JOIN [DESKTOP-DG326LV].BASEGENARO.DBO.LABORATORIO ON ID_LAB=ID_LAB1
	INNER JOIN [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDACC ON ID_MED=ID_MED3 
	INNER JOIN [DESKTOP-DG326LV].BASEGENARO.DBO.ACCIONTERAP ON ID_ACCT=ID_ACCT1
	WHERE NOM_LAB LIKE @CL+'%'
END   
GO

CREATE PROCEDURE BUS73
@CL VARCHAR(30)
AS
BEGIN
	SELECT NOM_MED,NOM_LAB,NOM_ACCT
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO 
	INNER JOIN [DESKTOP-DG326LV].BASEGENARO.DBO.LABORATORIO ON ID_LAB=ID_LAB1
	INNER JOIN [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDACC ON ID_MED=ID_MED3 
	INNER JOIN [DESKTOP-DG326LV].BASEGENARO.DBO.ACCIONTERAP ON ID_ACCT=ID_ACCT1
	WHERE NOM_ACCT LIKE @CL+'%'
END   
GO


--8

CREATE PROCEDURE BUS81
@CL VARCHAR(50)
AS
BEGIN
	SELECT NOM_MED,TIPO_PRES,CANT_UM,NOM_FARMACIA,FOLIO,PRECIO,STOCK
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO 
	INNER JOIN [USER-PC].BASEJORGE.DBO.FARMEDPREUN ON ID_MED=ID_MED1 
	INNER JOIN [DESKTOP-IUOOUHP].BASEBRIAN.DBO.PRESENTACION ON ID_PRES=ID_PRES1
	INNER JOIN [LAPTOP-IM7I95NH].BASEYAIR.DBO.UNIDADMEDIDA ON ID_UM=ID_UM1
	INNER JOIN [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA ON ID_FARMACIA=ID_FARMACIA2
	WHERE NOM_MED LIKE @CL+'%'
END   

GO

CREATE PROCEDURE BUS82
@CL VARCHAR(50)
AS
BEGIN
	SELECT NOM_MED,TIPO_PRES,CANT_UM,NOM_FARMACIA,FOLIO,PRECIO,STOCK
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO 
	INNER JOIN [USER-PC].BASEJORGE.DBO.FARMEDPREUN ON ID_MED=ID_MED1 
	INNER JOIN [DESKTOP-IUOOUHP].BASEBRIAN.DBO.PRESENTACION ON ID_PRES=ID_PRES1
	INNER JOIN [LAPTOP-IM7I95NH].BASEYAIR.DBO.UNIDADMEDIDA ON ID_UM=ID_UM1
	INNER JOIN [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA ON ID_FARMACIA=ID_FARMACIA2
	WHERE TIPO_PRES LIKE @CL+'%'
END   

GO


CREATE PROCEDURE BUS83
@CL VARCHAR(50)
AS
BEGIN
	SELECT NOM_MED,TIPO_PRES,CANT_UM,NOM_FARMACIA,FOLIO,PRECIO,STOCK
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO 
	INNER JOIN [USER-PC].BASEJORGE.DBO.FARMEDPREUN ON ID_MED=ID_MED1 
	INNER JOIN [DESKTOP-IUOOUHP].BASEBRIAN.DBO.PRESENTACION ON ID_PRES=ID_PRES1
	INNER JOIN [LAPTOP-IM7I95NH].BASEYAIR.DBO.UNIDADMEDIDA ON ID_UM=ID_UM1
	INNER JOIN [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA ON ID_FARMACIA=ID_FARMACIA2
	WHERE NOM_FARMACIA LIKE @CL+'%'
END   

GO

CREATE PROCEDURE BUS84
@CL VARCHAR(50)
AS
BEGIN
	SELECT NOM_MED,TIPO_PRES,CANT_UM,NOM_FARMACIA,FOLIO,PRECIO,STOCK
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO 
	INNER JOIN [USER-PC].BASEJORGE.DBO.FARMEDPREUN ON ID_MED=ID_MED1 
	INNER JOIN [DESKTOP-IUOOUHP].BASEBRIAN.DBO.PRESENTACION ON ID_PRES=ID_PRES1
	INNER JOIN [LAPTOP-IM7I95NH].BASEYAIR.DBO.UNIDADMEDIDA ON ID_UM=ID_UM1
	INNER JOIN [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA ON ID_FARMACIA=ID_FARMACIA2
	WHERE FOLIO LIKE @CL+'%'
END   
GO
CREATE PROCEDURE BUS85
@CL VARCHAR(50), @NM VARCHAR(50)
AS
BEGIN
	SELECT NOM_MED,TIPO_PRES,CANT_UM,NOM_FARMACIA,FOLIO,PRECIO,STOCK
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO 
	INNER JOIN [USER-PC].BASEJORGE.DBO.FARMEDPREUN ON ID_MED=ID_MED1 
	INNER JOIN [DESKTOP-IUOOUHP].BASEBRIAN.DBO.PRESENTACION ON ID_PRES=ID_PRES1
	INNER JOIN [LAPTOP-IM7I95NH].BASEYAIR.DBO.UNIDADMEDIDA ON ID_UM=ID_UM1
	INNER JOIN [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA ON ID_FARMACIA=ID_FARMACIA2
	WHERE  PRECIO LIKE @CL+'%' AND NOM_MED  LIKE @NM +'%'
END   
GO

CREATE PROCEDURE BUS86
@CL VARCHAR(50), @NM VARCHAR(50)
AS
BEGIN
	SELECT NOM_MED,TIPO_PRES,CANT_UM,NOM_FARMACIA,FOLIO,PRECIO,STOCK
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO 
	INNER JOIN [USER-PC].BASEJORGE.DBO.FARMEDPREUN ON ID_MED=ID_MED1 
	INNER JOIN [DESKTOP-IUOOUHP].BASEBRIAN.DBO.PRESENTACION ON ID_PRES=ID_PRES1
	INNER JOIN [LAPTOP-IM7I95NH].BASEYAIR.DBO.UNIDADMEDIDA ON ID_UM=ID_UM1
	INNER JOIN [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA ON ID_FARMACIA=ID_FARMACIA2
	WHERE STOCK LIKE @CL+'%' AND NOM_MED  LIKE @NM +'%'
END   



------ BUSQUEDAS COMPLEJAS
EXEC CONFD
EXEC BUS11 '1'
EXEC BUS12 'LUIS ALBERTO'
EXEC BUS13 'MIXTO'

EXEC CONC2
EXEC BUS21 '1'
EXEC BUS22 'HUGO'
EXEC BUS23 'Ingeniero ISC'
EXEC BUS24 'MATUTINO'

EXEC CONC3 
EXEC BUS31 'FARMACIA 1'
EXEC BUS32 'CELULAR'

EXEC CONC4 ------
EXEC BUS41 'BRIAN'
EXEC BUS42 'CASA'

EXEC CONC5
EXEC BUS51 'VIRGINIA'
EXEC BUS52 'FARMACIA 4'

EXEC CONC6
EXEC BUS61 'SALBUTAMOL'
EXEC BUS62 'TERAZOSINA'

EXEC CONC7
EXEC BUS71 'ASPIRINA'
EXEC BUS72 'LABORATORIO SAN ANGEL'
EXEC BUS73 'ALIVIO PARA COLICOS'

EXEC CONC8
EXEC BUS81 'AMLODIPINA'
EXEC BUS82 'Polvo'
EXEC BUS83 'FARMACIA 6'
EXEC BUS84 '2002'
EXEC BUS85 '234','PARACETAMOL'
EXEC BUS86 '55','LEXOTIROXINA'


---------------------------------------------------------------------------------
------------------------------ PROCEDIMIENTOS BÚSQUEDAS SIMPLES ---------------
---------------------------------------------------------------------------------

---- COLONIA (KEVIN / VICKY:)
CREATE PROCEDURE BSCOLONIA
@VAR VARCHAR(20)
AS BEGIN
	SELECT*
	FROM [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA
	WHERE ID_COL LIKE @VAR+'%'
END   

GO

---- ALCALDIA (MAURICIO)
CREATE PROCEDURE BSALCALDIA
@VAR VARCHAR(20)
AS BEGIN
	SELECT* 
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA
	WHERE ID_ALCA LIKE @VAR+'%'
END   
GO

---- ACCIONTERAP (GENARO / VICKY:)
CREATE PROCEDURE BSACCIONTERAP
@VAR VARCHAR(20)
AS BEGIN
	SELECT* 
	FROM [DESKTOP-DG326LV].BASEGENARO.DBO.ACCIONTERAP
	WHERE ID_ACCT LIKE @VAR+'%'
END   

GO

---- MONODROGA (YAIR)
CREATE PROCEDURE BSMONODROGA
@VAR VARCHAR(20)
AS BEGIN
	SELECT* 
	FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.MONODROGA
	WHERE ID_MONO LIKE @VAR+'%'
END   
GO
---- LABORATORIO (GENARO / VICKY:)
CREATE PROCEDURE BSLABORATORIO
@VAR VARCHAR(20)
AS BEGIN
	SELECT* 
	FROM [DESKTOP-DG326LV].BASEGENARO.DBO.LABORATORIO
	WHERE ID_LAB LIKE @VAR+'%'
END   
GO
---- UNIDADMEDIDA (YAIR)
CREATE PROCEDURE BSUNIDADMEDIDA
@VAR VARCHAR(20) 
AS BEGIN
	SELECT* 
	FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.UNIDADMEDIDA
	WHERE ID_UM LIKE @VAR+'%'
END   
GO

---- PRESENTACION (BRIAN)
CREATE PROCEDURE BSPRESENTACION 
@VAR VARCHAR(20) 
AS BEGIN
	SELECT* 
	FROM [DESKTOP-IUOOUHP].BASEBRIAN.DBO.PRESENTACION 
	WHERE ID_PRES LIKE @VAR+'%'
END   
GO
---- PUESTO (MARCO)
CREATE PROCEDURE BSPUESTO
@VAR VARCHAR(20) 
AS BEGIN
	SELECT* 
	FROM [DESKTOP-CGC0VV9].BASEMARCO.DBO.PUESTO
	WHERE ID_PUESTO LIKE @VAR+'%'
END   
GO
---- TIPOTEL (GENARO / VICKY:)
CREATE PROCEDURE BSTIPOTELF
@VAR VARCHAR(20) 
AS BEGIN
	SELECT* 
	FROM [DESKTOP-DG326LV].BASEGENARO.DBO.TIPOTELF
	WHERE ID_TIPOTELF LIKE @VAR+'%'
END   
GO
---- CIUDAD (KEVIN / VICKY:)
CREATE PROCEDURE BSCIUDAD
@VAR VARCHAR(20) 
AS BEGIN
	SELECT* 
	FROM  [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD
	WHERE ID_CIU LIKE @VAR+'%'
END   
GO
---- HORARIO (ULISES)
CREATE PROCEDURE BSHORARIO
@VAR VARCHAR(20) 
AS BEGIN
	SELECT* 
	FROM [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO
	WHERE ID_HOR LIKE @VAR+'%'
END   
GO
---- CALLE (ULISES)
CREATE PROCEDURE BSCALLE
@VAR VARCHAR(20) 
AS BEGIN
	SELECT* 
	FROM [DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE
	WHERE ID_CALLE LIKE @VAR+'%'
END   
GO
---- MEDICAMENTO (MAURICIO)
CREATE PROCEDURE BSMEDICAMENTO
@VAR VARCHAR(20) 
AS BEGIN
	SELECT* 
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO
	WHERE ID_MED LIKE @VAR+'%'
END   
GO
---- EMPLEADO (BRIAN)
CREATE PROCEDURE BSEMPLEADO 
@VAR VARCHAR(20) 
AS BEGIN
	SELECT* 
	FROM [DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO
	WHERE ID_EMP LIKE @VAR+'%'
END   
GO
---- FARMACEUTICO (MARCO)
CREATE PROCEDURE BSFARMACEUTICO 
@VAR VARCHAR(20) 
AS BEGIN
	SELECT* 
	FROM [DESKTOP-CGC0VV9].BASEMARCO.DBO.FARMACEUTICO
	WHERE ID_FAR LIKE @VAR+'%'
END   
GO
---- FARMACIA (YAIR)
CREATE PROCEDURE BSFARMACIA
@VAR VARCHAR(20) 
AS BEGIN
	SELECT* 
	FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA
	WHERE ID_FARMACIA LIKE @VAR+'%'
END   
GO
---- MEDACC (MAURICIO)
CREATE PROCEDURE BSMEDACC
@VAR VARCHAR(20) 
AS BEGIN
	SELECT* 
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDACC
	WHERE ID_MED3 LIKE @VAR+'%' 
END   
GO
CREATE PROCEDURE BSMEDACC2
@VAR VARCHAR(20) 
AS BEGIN
	SELECT* 
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDACC
	WHERE ID_ACCT1 LIKE @VAR+'%' 
END   
GO

---- MEDMONO (KEVIN / VICKY:)
CREATE PROCEDURE BSMEDMONO
@VAR VARCHAR(20) 
AS BEGIN
	SELECT* 
	FROM [LAPTOP-61QAQSQG].BASEKEVS.DBO.MEDMONO
	WHERE ID_MED2 LIKE @VAR+'%' 
END   
GO
CREATE PROCEDURE BSMEDMONO2
@VAR VARCHAR(20) 
AS BEGIN
	SELECT* 
	FROM [LAPTOP-61QAQSQG].BASEKEVS.DBO.MEDMONO
	WHERE ID_MONO1 LIKE @VAR+'%' 
END   
GO
---- FARMEDPREUN (JORGE)
CREATE PROCEDURE BSFARMEDPREUN
@VAR VARCHAR(20) 
AS BEGIN
	SELECT* 
	FROM [USER-PC].BASEJORGE.DBO.FARMEDPREUN
	WHERE FOLIO LIKE @VAR+'%' 
END   
GO
---- FARMTIPO (JORGE)
CREATE PROCEDURE BSFARMTIPO
@VAR VARCHAR(20) 
AS BEGIN
	SELECT* 
	FROM [USER-PC].BASEJORGE.DBO.FARMTIPO
	WHERE ID_FARMACIA1 LIKE @VAR+'%' 
END   
GO
	CREATE PROCEDURE BSFARMTIPO2
	@VAR VARCHAR(20) 
	AS BEGIN
		SELECT* 
		FROM [USER-PC].BASEJORGE.DBO.FARMTIPO
		WHERE ID_TIPOTELF2 LIKE @VAR+'%' 
	END   
GO
	CREATE PROCEDURE BSFARMTIPO3
	@VAR VARCHAR(20) 
	AS BEGIN
		SELECT* 
		FROM [USER-PC].BASEJORGE.DBO.FARMTIPO
		WHERE TELEFONO2 LIKE @VAR+'%' 
	END   
	GO
---- EMPTIPO (ULISES)
CREATE PROCEDURE BSEMPTIPO
@VAR VARCHAR(20) 
AS BEGIN
	SELECT* 
	FROM [DESKTOP-CJ3JHQ2].BASEULI.DBO.EMPTIPO
	WHERE ID_EMP1 LIKE @VAR+'%' 

END   
GO
	CREATE PROCEDURE BSEMPTIPO2
	@VAR VARCHAR(20) 
	AS BEGIN
		SELECT* 
		FROM [DESKTOP-CJ3JHQ2].BASEULI.DBO.EMPTIPO
		WHERE ID_TIPOTELF1 LIKE @VAR+'%' 
	END   
	GO

	CREATE PROCEDURE BSEMPTIPO3
	@VAR VARCHAR(20) 
	AS BEGIN
		SELECT* 
		FROM [DESKTOP-CJ3JHQ2].BASEULI.DBO.EMPTIPO
		WHERE TELEFONO1 LIKE @VAR+'%' 
	END   
	

---------------------------------------------------------------------------------
------------------------------ PROCEDIMIENTOS INGRESOS  -------------------------
---------------------------------------------------------------------------------
---- COLONIA (KEVIN)
CREATE  PROCEDURE INGCOLONIA
@VAR VARCHAR(15), @NOMC VARCHAR (40) 
AS 
BEGIN
	IF ((EXISTS(SELECT * FROM [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA WHERE @VAR=ID_COL)))

	BEGIN	
		PRINT 'ERROR, CLAVE EXISTENTE'
	END   
	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA  VALUES 
			(char(67) + char(79) +char(76) +char(69)+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)as varchar(2))+
			CHAR(ROUND(((90-65)*RAND()+65),0))+ CHAR(ROUND(((90-65)*RAND()+65),0))
			+CHAR(ROUND(((90-65)*RAND()+65),0))+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)
			as varchar(2))+CHAR(ROUND(((90-65)*RAND()+65),0))+
			cast(cast(ROUND(((9-1)*RAND()+1),0)as int)as varchar(1)), UPPER(@NOMC))
		END   
END   
GO

---- ALCALDIA (MAURICIO)
CREATE  PROCEDURE INGALCALDIA
@VAR VARCHAR(15), @NOMC VARCHAR (40) 
AS 
BEGIN
	IF ((EXISTS(SELECT * FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA WHERE @VAR=ID_ALCA)))

	BEGIN	
		PRINT 'ERROR, CLAVE EXISTENTE'
	END   
	
	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA  VALUES 
			(char(65) + char(76) +char(67) +char(69)+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)as varchar(2))+
			CHAR(ROUND(((90-65)*RAND()+65),0))+ CHAR(ROUND(((90-65)*RAND()+65),0))
			+CHAR(ROUND(((90-65)*RAND()+65),0))+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)
			as varchar(2))+CHAR(ROUND(((90-65)*RAND()+65),0))+
			cast(cast(ROUND(((9-1)*RAND()+1),0)as int)as varchar(1)), UPPER(@NOMC))
		END   
END   
GO

---- ACCIONTERAP (GENARO)
CREATE  PROCEDURE INGACCIONTERAP
@VAR VARCHAR(15), @NOMC VARCHAR (40) 
AS 
BEGIN
	IF ((EXISTS(SELECT * FROM [DESKTOP-DG326LV].BASEGENARO.DBO.ACCIONTERAP WHERE @VAR=ID_ACCT)))

	BEGIN	
		PRINT 'ERROR, CLAVE EXISTENTE'
	END   

	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [DESKTOP-DG326LV].BASEGENARO.DBO.ACCIONTERAP  VALUES 
			(char(65) + char(67) +char(67) +char(84)+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)as varchar(2))+
			CHAR(ROUND(((90-65)*RAND()+65),0))+ CHAR(ROUND(((90-65)*RAND()+65),0))
			+CHAR(ROUND(((90-65)*RAND()+65),0))+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)
			as varchar(2))+CHAR(ROUND(((90-65)*RAND()+65),0))+
			cast(cast(ROUND(((9-1)*RAND()+1),0)as int)as varchar(1)), UPPER(@NOMC))
		END   
END   
GO

---- MONODROGA (YAIR)
CREATE  PROCEDURE INGMONODROGA
@VAR VARCHAR(15), @NOMC VARCHAR (40) 
AS 
BEGIN
	IF ((EXISTS(SELECT * FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.MONODROGA WHERE @VAR=ID_MONO)))

	BEGIN	
		PRINT 'ERROR, CLAVE EXISTENTE'
	END   

	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [LAPTOP-IM7I95NH].BASEYAIR.DBO.MONODROGA  VALUES 
			(char(77) + char(79) +char(78) +char(68)+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)as varchar(2))+
			CHAR(ROUND(((90-65)*RAND()+65),0))+ CHAR(ROUND(((90-65)*RAND()+65),0))
			+CHAR(ROUND(((90-65)*RAND()+65),0))+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)
			as varchar(2))+CHAR(ROUND(((90-65)*RAND()+65),0))+
			cast(cast(ROUND(((9-1)*RAND()+1),0)as int)as varchar(1)), UPPER(@NOMC))
		END   
END   
GO

---- LABORATORIO (GENARO)
CREATE  PROCEDURE INGLABORATORIO
@VAR VARCHAR(15), @NOMC VARCHAR (40) 
AS 
BEGIN
	IF ((EXISTS(SELECT * FROM [DESKTOP-DG326LV].BASEGENARO.DBO.LABORATORIO WHERE @VAR=ID_LAB)))

	BEGIN	
		PRINT 'ERROR, CLAVE EXISTENTE'
	END   

	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [DESKTOP-DG326LV].BASEGENARO.DBO.LABORATORIO  VALUES 
			(char(76) + char(65) +char(66)+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)as varchar(2))+
			CHAR(ROUND(((90-65)*RAND()+65),0))+ CHAR(ROUND(((90-65)*RAND()+65),0))
			+CHAR(ROUND(((90-65)*RAND()+65),0))+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)
			as varchar(2))+CHAR(ROUND(((90-65)*RAND()+65),0))+
			cast(cast(ROUND(((9-1)*RAND()+1),0)as int)as varchar(1)), UPPER(@NOMC))
		END   
END   
GO
---- UNIDADMEDIDA (YAIR)
CREATE  PROCEDURE INGUNIDADMEDIDA
@VAR VARCHAR(15), @NOMC VARCHAR (40) 
AS 
BEGIN
	IF ((EXISTS(SELECT * FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.UNIDADMEDIDA WHERE @VAR=ID_UM)))

	BEGIN	
		PRINT 'ERROR, CLAVE EXISTENTE'
	END   

	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [LAPTOP-IM7I95NH].BASEYAIR.DBO.UNIDADMEDIDA  VALUES 
			(char(85) + char(68) +char(77)+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)as varchar(2))+
			CHAR(ROUND(((90-65)*RAND()+65),0))+ CHAR(ROUND(((90-65)*RAND()+65),0))
			+CHAR(ROUND(((90-65)*RAND()+65),0))+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)
			as varchar(2))+CHAR(ROUND(((90-65)*RAND()+65),0))+
			cast(cast(ROUND(((9-1)*RAND()+1),0)as int)as varchar(1)), UPPER(@NOMC))
		END   
END   
GO

---- PRESENTACION (BRIAN)
CREATE  PROCEDURE INGPRESENTACION
@VAR VARCHAR(15), @NOMC VARCHAR (40) 
AS 
BEGIN
	IF ((EXISTS(SELECT * FROM [DESKTOP-IUOOUHP].BASEBRIAN.DBO.PRESENTACION WHERE @VAR=ID_PRES)))

	BEGIN	
		PRINT 'ERROR, CLAVE EXISTENTE'
	END   

	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [DESKTOP-IUOOUHP].BASEBRIAN.DBO.PRESENTACION  VALUES 
			(char(80) + char(82) +char(69)+char(83)+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)as varchar(2))+
			CHAR(ROUND(((90-65)*RAND()+65),0))+ CHAR(ROUND(((90-65)*RAND()+65),0))
			+CHAR(ROUND(((90-65)*RAND()+65),0))+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)
			as varchar(2))+CHAR(ROUND(((90-65)*RAND()+65),0))+
			cast(cast(ROUND(((9-1)*RAND()+1),0)as int)as varchar(1)), UPPER(@NOMC))
		END   
END   
GO
---- PUESTO (MARCO)
CREATE  PROCEDURE INGPUESTO
@VAR VARCHAR(15), @NOMC VARCHAR (40) 
AS 
BEGIN
	IF ((EXISTS(SELECT * FROM [DESKTOP-CGC0VV9].BASEMARCO.DBO.PUESTO WHERE @VAR=ID_PUESTO)))

	BEGIN	
		PRINT 'ERROR, CLAVE EXISTENTE'
	END   

	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [DESKTOP-CGC0VV9].BASEMARCO.DBO.PUESTO  VALUES 
			(char(80) + char(85) +char(69)+char(83)+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)as varchar(2))+
			CHAR(ROUND(((90-65)*RAND()+65),0))+ CHAR(ROUND(((90-65)*RAND()+65),0))
			+CHAR(ROUND(((90-65)*RAND()+65),0))+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)
			as varchar(2))+CHAR(ROUND(((90-65)*RAND()+65),0))+
			cast(cast(ROUND(((9-1)*RAND()+1),0)as int)as varchar(1)), UPPER(@NOMC))
		END   
END   
GO

---- TIPOTELF (GENARO)
CREATE  PROCEDURE INGTIPOTELF
@VAR VARCHAR(15), @NOMC VARCHAR (40) 
AS 
BEGIN
	IF ((EXISTS(SELECT * FROM [DESKTOP-DG326LV].BASEGENARO.DBO.TIPOTELF WHERE @VAR=ID_TIPOTELF)))

	BEGIN	
		PRINT 'ERROR, CLAVE EXISTENTE'
	END   

	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [DESKTOP-DG326LV].BASEGENARO.DBO.TIPOTELF  VALUES 
			(char(84) + char(84) +char(69)+char(76)+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)as varchar(2))+
			CHAR(ROUND(((90-65)*RAND()+65),0))+ CHAR(ROUND(((90-65)*RAND()+65),0))
			+CHAR(ROUND(((90-65)*RAND()+65),0))+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)
			as varchar(2))+CHAR(ROUND(((90-65)*RAND()+65),0))+
			cast(cast(ROUND(((9-1)*RAND()+1),0)as int)as varchar(1)), UPPER(@NOMC))
		END   
END   
GO

---- CIUDAD (KEVIN)
CREATE  PROCEDURE INGCIUDAD
@VAR VARCHAR(15), @NOMC VARCHAR (40) 
AS 
BEGIN
	IF ((EXISTS(SELECT * FROM [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD WHERE @VAR=ID_CIU)))

	BEGIN	
		PRINT 'ERROR, CLAVE EXISTENTE'
	END   

	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD  VALUES 
			(char(67) + char(73) +char(85)+char(68)+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)as varchar(2))+
			CHAR(ROUND(((90-65)*RAND()+65),0))+ CHAR(ROUND(((90-65)*RAND()+65),0))
			+CHAR(ROUND(((90-65)*RAND()+65),0))+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)
			as varchar(2))+CHAR(ROUND(((90-65)*RAND()+65),0))+
			cast(cast(ROUND(((9-1)*RAND()+1),0)as int)as varchar(1)), UPPER(@NOMC))
		END   
END   
GO
---- HORARIO (ULISES)
CREATE  PROCEDURE INGHORARIO
@VAR VARCHAR(15), @NOMC VARCHAR (40) 
AS 
BEGIN
	IF ((EXISTS(SELECT * FROM [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO WHERE @VAR=ID_HOR)))

	BEGIN	
		PRINT 'ERROR, CLAVE EXISTENTE'
	END   

	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO  VALUES 
			(char(72) + char(79) +char(82)+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)as varchar(2))+
			CHAR(ROUND(((90-65)*RAND()+65),0))+ CHAR(ROUND(((90-65)*RAND()+65),0))
			+CHAR(ROUND(((90-65)*RAND()+65),0))+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)
			as varchar(2))+CHAR(ROUND(((90-65)*RAND()+65),0))+
			cast(cast(ROUND(((9-1)*RAND()+1),0)as int)as varchar(1)), UPPER(@NOMC))
		END   
END   
GO

---- CALLE (ULISES)
CREATE  PROCEDURE INGCALLE
@VAR VARCHAR(15), @NOMC VARCHAR (40) 
AS 
BEGIN
	IF ((EXISTS(SELECT * FROM [DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE WHERE @VAR=ID_CALLE)))

	BEGIN	
		PRINT 'ERROR, CLAVE EXISTENTE'
	END   

	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE  VALUES 
			(char(67) + char(65) +char(76)+char(76)+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)as varchar(2))+
			CHAR(ROUND(((90-65)*RAND()+65),0))+ CHAR(ROUND(((90-65)*RAND()+65),0))
			+CHAR(ROUND(((90-65)*RAND()+65),0))+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)
			as varchar(2))+CHAR(ROUND(((90-65)*RAND()+65),0))+
			cast(cast(ROUND(((9-1)*RAND()+1),0)as int)as varchar(1)), UPPER(@NOMC))
		END   
END   
GO

---- MEDICAMENTO (MAURICIO)
CREATE  PROCEDURE INGMEDICAMENTO
@VAR VARCHAR(15), @NOMC VARCHAR (40) , @IDLB1 VARCHAR (15) 
AS 
BEGIN
	IF ((EXISTS(SELECT * FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO WHERE @VAR=ID_MED)))

	BEGIN	
		PRINT 'ERROR, CLAVE EXISTENTE'
	END   

	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO  VALUES 
			(char(77) + char(69) +char(68)+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)as varchar(2))+
			CHAR(ROUND(((90-65)*RAND()+65),0))+ CHAR(ROUND(((90-65)*RAND()+65),0))
			+CHAR(ROUND(((90-65)*RAND()+65),0))+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)
			as varchar(2))+CHAR(ROUND(((90-65)*RAND()+65),0))+
			cast(cast(ROUND(((9-1)*RAND()+1),0)as int)as varchar(1)), UPPER(@NOMC), UPPER(@IDLB1))
		END   
END   
GO

---- EMPLEADO (BRIAN)
CREATE  PROCEDURE INGEMPLEADO
@VAR VARCHAR(15), @AP VARCHAR (40), @AM VARCHAR (40), @NOMC VARCHAR (40), @NX INT, @CP VARCHAR (15), @FN DATE, 
@IDCA1 VARCHAR(15),@IDCOL1 VARCHAR(15),@IDAL1 VARCHAR(15),@IDCIU1 VARCHAR(15),@IDP1 VARCHAR(15),@IDHR1 VARCHAR(15),@IDFAR4 VARCHAR(15)
AS 
BEGIN
	IF ((NOT EXISTS(SELECT * FROM[DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE WHERE  @IDCA1=ID_CALLE))  OR
		(NOT EXISTS(SELECT * FROM [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA WHERE @IDCOL1=ID_COL)) OR
		(NOT EXISTS(SELECT * FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA WHERE  @IDAL1=ID_ALCA)) OR 
		(NOT EXISTS(SELECT *  FROM [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD  WHERE @IDCIU1=ID_CIU)) OR 
		(NOT EXISTS(SELECT *  FROM [DESKTOP-CGC0VV9].BASEMARCO.DBO.PUESTO  WHERE @IDP1=ID_PUESTO)) OR 
		(NOT EXISTS(SELECT *  FROM [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO  WHERE @IDHR1=ID_HOR)) OR 
		(NOT EXISTS(SELECT * FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA WHERE  @IDFAR4=ID_FARMACIA)))

	BEGIN
		PRINT 'CLAVES FORANEAS NO ENCONTRADAS'
	END   

	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO  VALUES 
			(char(69) + char(77) +char(80)+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)as varchar(2))+
			CHAR(ROUND(((90-65)*RAND()+65),0))+ CHAR(ROUND(((90-65)*RAND()+65),0))
			+CHAR(ROUND(((90-65)*RAND()+65),0))+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)
			as varchar(2))+CHAR(ROUND(((90-65)*RAND()+65),0))+
			cast(cast(ROUND(((9-1)*RAND()+1),0)as int)as varchar(1)), UPPER(@AP), UPPER(@AM), UPPER(@NOMC), (@NX), (@CP), @FN, 
																	  UPPER(@IDCA1), UPPER(@IDCOL1) , UPPER(@IDAL1), UPPER(@IDCIU1), UPPER(@IDP1), UPPER(@IDHR1), UPPER(@IDFAR4))
		END   
END   
GO
set dateformat DMY

---- FARMACEUTICO (MARCO)
CREATE  PROCEDURE INGFARMACEUTICO
@IDF VARCHAR(15), @AP VARCHAR(20), @AM VARCHAR(20), @NOM VARCHAR(30), @ND INT, @CP INT, @CED INT, @CORREO VARCHAR(25), 
@IDC2 VARCHAR(15), @IDCOL2 VARCHAR(15), @IDDEL2 VARCHAR(15), @IDCD2 VARCHAR(15),@IDH2 VARCHAR(15)
AS 
BEGIN
	IF ((NOT EXISTS(SELECT * FROM[DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE WHERE  @IDC2=ID_CALLE))  OR
		(NOT EXISTS(SELECT * FROM [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA WHERE @IDCOL2=ID_COL)) OR
		(NOT EXISTS(SELECT * FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA WHERE  @IDDEL2=ID_ALCA)) OR
		(NOT EXISTS(SELECT *  FROM [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD  WHERE @IDCD2=ID_CIU)) OR
		(NOT EXISTS(SELECT * FROM [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO  WHERE  @IDH2=ID_HOR)))

	BEGIN
		PRINT 'CLAVES FORANEAS NO ENCONTRADAS'
	END   

	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [DESKTOP-CGC0VV9].BASEMARCO.DBO.FARMACEUTICO VALUES 
			(char(70)+char(65)+char(82)+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)as varchar(2))+
			CHAR(ROUND(((90-65)*RAND()+65),0))+ CHAR(ROUND(((90-65)*RAND()+65),0))
			+CHAR(ROUND(((90-65)*RAND()+65),0))+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)
			as varchar(2))+CHAR(ROUND(((90-65)*RAND()+65),0))+
			cast(cast(ROUND(((9-1)*RAND()+1),0)as int)as varchar(1)), UPPER( @AP) , UPPER(@AM) , UPPER(@NOM), @ND , @CP, UPPER(@CED), 
			UPPER(@CORREO), UPPER(@IDC2) , UPPER(@IDCOL2), UPPER(@IDDEL2), UPPER(@IDCD2), UPPER(@IDH2))
		END   
END   
GO

---- FARMACIA (YAIR)
CREATE  PROCEDURE INGFARMACIA
@IDFA VARCHAR(15), @NOM VARCHAR(100), @DIR VARCHAR(150), @IDFR1 VARCHAR(15)
AS 
BEGIN
	IF ((NOT EXISTS(SELECT * FROM [DESKTOP-CGC0VV9].BASEMARCO.DBO.FARMACEUTICO WHERE  @IDFR1=ID_FAR)))

	BEGIN
		PRINT 'CLAVES FORANEAS NO ENCONTRADAS'
	END   

	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA VALUES 
			(char(70)+char(65)+char(82)+char(77)+char(65)+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)as varchar(2))+
			CHAR(ROUND(((90-65)*RAND()+65),0))+ CHAR(ROUND(((90-65)*RAND()+65),0))
			+CHAR(ROUND(((90-65)*RAND()+65),0))+cast(cast(ROUND(((99-10)*RAND()+10),0)as int)
			as varchar(2))+CHAR(ROUND(((90-65)*RAND()+65),0))+
			cast(cast(ROUND(((9-1)*RAND()+1),0)as int)as varchar(1)), UPPER( @NOM) , UPPER(@DIR) , UPPER(@IDFR1))
		END   
END   
GO

---- MEDACC (MAURICIO)
CREATE  PROCEDURE INGMEDACC
@IDMD3 VARCHAR(15), @IDACC1 VARCHAR(15)
AS 
BEGIN
	IF ((NOT EXISTS(SELECT *  FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO  WHERE @IDMD3=ID_MED)) OR
		(NOT EXISTS(SELECT * FROM [DESKTOP-DG326LV].BASEGENARO.DBO.ACCIONTERAP  WHERE  @IDACC1=ID_ACCT)))

	BEGIN
		PRINT 'CLAVES FORANEAS NO ENCONTRADAS'
	END   

	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDACC VALUES (UPPER(@IDMD3) , UPPER(@IDACC1))
		END   
END   
GO

---- MEDMONO (KEVIN)
CREATE  PROCEDURE INGMEDMONO
@IDMD2 VARCHAR(15), @IDMON1 VARCHAR(15)
AS 
BEGIN
	IF ((NOT EXISTS(SELECT *  FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO  WHERE @IDMD2=ID_MED)) OR
		(NOT EXISTS(SELECT * FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.MONODROGA  WHERE  @IDMON1=ID_MONO)))

	BEGIN
		PRINT 'CLAVES FORANEAS NO ENCONTRADAS'
	END   

	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [LAPTOP-61QAQSQG].BASEKEVS.DBO.MEDMONO VALUES (UPPER(@IDMD2) , UPPER(@IDMON1))
		END   
END   
GO

---- FARMEDPREUN (KEVIN)
CREATE  PROCEDURE INGFARMEDPREUN
@IDFA2 VARCHAR(15), @IDM1 VARCHAR(15), @IDP1 VARCHAR(15), @IDUM1 VARCHAR(15),
@F VARCHAR (10), @P SMALLINT, @S SMALLINT
AS 
BEGIN
	IF ((NOT EXISTS(SELECT *  FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA  WHERE @IDFA2=ID_FARMACIA)) OR
		(NOT EXISTS(SELECT * FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO  WHERE  @IDM1=ID_MED))OR
		(NOT EXISTS(SELECT * FROM [DESKTOP-IUOOUHP].BASEBRIAN.DBO.PRESENTACION  WHERE  @IDP1=ID_PRES))OR
		(NOT EXISTS(SELECT * FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.UNIDADMEDIDA  WHERE  @IDUM1=ID_UM)))

	BEGIN
		PRINT 'CLAVES FORANEAS NO ENCONTRADAS'
	END   

	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [USER-PC].BASEJORGE.DBO.FARMEDPREUN VALUES (UPPER(@IDFA2) , UPPER(@IDM1), UPPER(@IDP1), UPPER(@IDUM1), UPPER(@F), @P, @S)
		END   
END   
GO


---- FARMTIPO (JORGE)
CREATE  PROCEDURE INGFARMTIPO
@IDFA1 VARCHAR(15), @IDTT2 VARCHAR(15), @TEL2 VARCHAR(12)
AS 
BEGIN
	IF ((NOT EXISTS(SELECT *  FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA  WHERE @IDFA1=ID_FARMACIA)) OR
		(NOT EXISTS(SELECT * FROM [DESKTOP-DG326LV].BASEGENARO.DBO.TIPOTELF  WHERE  @IDTT2=ID_TIPOTELF)))

	BEGIN
		PRINT 'CLAVES FORANEAS NO ENCONTRADAS'
	END   

	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [USER-PC].BASEJORGE.DBO.FARMTIPO VALUES (UPPER(@IDFA1) , UPPER(@IDTT2), @TEL2)
		END   
END   
GO

---- EMPTIPO (ULISES)
CREATE  PROCEDURE INGEMPTIPO
@IDE1 VARCHAR(15), @IDTT1 VARCHAR(15), @TEL1 VARCHAR(15)
AS 
BEGIN
	IF ((NOT EXISTS(SELECT *  FROM	[DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO  WHERE @IDE1=ID_EMP)) OR
		(NOT EXISTS(SELECT * FROM [DESKTOP-DG326LV].BASEGENARO.DBO.TIPOTELF  WHERE  @IDTT1=ID_TIPOTELF)))

	BEGIN
		PRINT 'CLAVES FORANEAS NO ENCONTRADAS'
	END   

	ELSE 
		BEGIN 
			PRINT 'DATOS ALMACENADOS CORRECTAMENTE'
			INSERT INTO [DESKTOP-CJ3JHQ2].BASEULI.DBO.EMPTIPO VALUES (UPPER(@IDE1) , UPPER(@IDTT1), @TEL1)
		END   
END   

---------------------------------------------------------------------------------
------------------------------ PROCEDIMIENTOS ELIMINACIONES  -------------------------
---------------------------------------------------------------------------------
-----------------------------------------------
--------
CREATE  PROCEDURE ELIMCOLONIA
@VAR VARCHAR(15)
AS
BEGIN
	DELETE 
	FROM [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA
	WHERE ID_COL=@VAR 

	UPDATE [DESKTOP-CGC0VV9].BASEMARCO.DBO.FARMACEUTICO
	SET ID_COL2=NULL
	WHERE ID_COL2=@VAR

	UPDATE [DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO 
	SET ID_COL1=NULL
	WHERE ID_COL1=@VAR

END   
GO
--------
CREATE  PROCEDURE ELIMALCALDIA
@VAR VARCHAR(15)
AS
BEGIN
	DELETE 
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA
	WHERE ID_ALCA=@VAR 

	UPDATE [DESKTOP-CGC0VV9].BASEMARCO.DBO.FARMACEUTICO
	SET ID_ALCA2=NULL
	WHERE ID_ALCA2=@VAR

	UPDATE [DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO 
	SET ID_ALCA1=NULL
	WHERE ID_ALCA1=@VAR
END   
GO
--------
CREATE  PROCEDURE ELIMACCIONTERAP
@VAR VARCHAR(15)
AS
BEGIN
	DELETE 
	FROM [DESKTOP-DG326LV].BASEGENARO.DBO.ACCIONTERAP
	WHERE ID_ACCT=@VAR 

	UPDATE [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDACC
	SET ID_ACCT1=NULL
	WHERE ID_ACCT1=@VAR
END   
GO
--------
CREATE  PROCEDURE ELIMMONODROGA
@VAR VARCHAR(15)
AS
BEGIN
	DELETE 
	FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.MONODROGA
	WHERE ID_MONO=@VAR 

	UPDATE [LAPTOP-61QAQSQG].BASEKEVS.DBO.MEDMONO
	SET ID_MONO1=NULL
	WHERE ID_MONO1=@VAR
END   
GO
--------
CREATE  PROCEDURE ELIMLABORATORIO
@VAR VARCHAR(15)
AS
BEGIN
	DELETE 
	FROM [DESKTOP-DG326LV].BASEGENARO.DBO.LABORATORIO
	WHERE ID_LAB=@VAR 

	UPDATE [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO
	SET ID_LAB1=NULL
	WHERE ID_LAB1=@VAR
END   

GO
--------
CREATE  PROCEDURE ELIMUNIDADMEDIDA
@VAR VARCHAR(15)
AS
BEGIN
	DELETE 
	FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.UNIDADMEDIDA
	WHERE ID_UM=@VAR 

	UPDATE [USER-PC].BASEJORGE.DBO.FARMEDPREUN
	SET ID_UM1=NULL
	WHERE ID_UM1=@VAR

END   
GO
--------
CREATE  PROCEDURE ELIMPRESENTACION
@VAR VARCHAR(15)
AS
BEGIN
	DELETE 
	FROM [DESKTOP-IUOOUHP].BASEBRIAN.DBO.PRESENTACION
	WHERE ID_PRES=@VAR 

	UPDATE [USER-PC].BASEJORGE.DBO.FARMEDPREUN
	SET ID_PRES1=NULL
	WHERE ID_PRES1=@VAR

END   

GO
--------
CREATE  PROCEDURE ELIMPUESTO
@VAR VARCHAR(15)
AS
BEGIN
	DELETE 
	FROM [DESKTOP-CGC0VV9].BASEMARCO.DBO.PUESTO
	WHERE ID_PUESTO=@VAR 

	UPDATE [DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO
	SET ID_PUESTO1=NULL
	WHERE ID_PUESTO1=@VAR
END   
GO
--------
CREATE  PROCEDURE ELIMTIPOTELF
@VAR VARCHAR(15)
AS
BEGIN
	DELETE 
	FROM [DESKTOP-DG326LV].BASEGENARO.DBO.TIPOTELF
	WHERE ID_TIPOTELF=@VAR 

	UPDATE [USER-PC].BASEJORGE.DBO.FARMTIPO
	SET ID_TIPOTELF2=NULL
	WHERE ID_TIPOTELF2=@VAR

	UPDATE [DESKTOP-CJ3JHQ2].BASEULI.DBO.EMPTIPO
	SET ID_TIPOTELF1=NULL
	WHERE ID_TIPOTELF1=@VAR
END   
GO
--------
CREATE  PROCEDURE ELIMCIUDAD
@VAR VARCHAR(15)
AS
BEGIN
	DELETE 
	FROM [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD
	WHERE ID_CIU=@VAR

	UPDATE [DESKTOP-CGC0VV9].BASEMARCO.DBO.FARMACEUTICO
	SET ID_CIU2=NULL
	WHERE ID_CIU2=@VAR

	UPDATE [DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO
	SET ID_CIU1=NULL
	WHERE ID_CIU1=@VAR
END   
GO
--------
CREATE  PROCEDURE ELIMHORARIO
@VAR VARCHAR(15)
AS
BEGIN
	DELETE 
	FROM [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO
	WHERE ID_HOR=@VAR

	UPDATE [DESKTOP-CGC0VV9].BASEMARCO.DBO.FARMACEUTICO
	SET ID_HOR2=NULL
	WHERE ID_HOR2=@VAR

	UPDATE [DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO
	SET ID_HOR1=NULL
	WHERE ID_HOR1=@VAR
END   
GO
--------------- ALTERNATIVA 2
CREATE  PROCEDURE ELIMCALLE1
@CLAVE VARCHAR(15)
AS
BEGIN
	DELETE 
	FROM [DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE
	WHERE ID_CALLE=@CLAVE

	UPDATE [DESKTOP-CGC0VV9].BASEMARCO.DBO.FARMACEUTICO
	SET ID_CALLE2=NULL
	WHERE ID_CALLE2=@CLAVE

	UPDATE [DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO
	SET ID_CALLE1=NULL
	WHERE ID_CALLE1=@CLAVE
END   
GO
--------
CREATE  PROCEDURE ELIMMEDICAMENTO
@VAR VARCHAR(15)
AS
BEGIN
	DELETE 
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO
	WHERE ID_MED=@VAR 

	UPDATE [LAPTOP-61QAQSQG].BASEKEVS.DBO.MEDMONO
	SET ID_MED2=NULL
	WHERE ID_MED2=@VAR

	UPDATE [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDACC
	SET ID_MED3=NULL
	WHERE ID_MED3=@VAR

	UPDATE [USER-PC].BASEJORGE.DBO.FARMEDPREUN
	SET ID_MED1=NULL
	WHERE ID_MED1=@VAR
END   

GO
--------
CREATE  PROCEDURE ELIMEMPLEADO
@VAR VARCHAR(15)
AS
BEGIN
	DELETE 
	FROM [DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO
	WHERE ID_EMP=@VAR 

	UPDATE [DESKTOP-CJ3JHQ2].BASEULI.DBO.EMPTIPO
	SET ID_EMP1=NULL
	WHERE ID_EMP1=@VAR

END   
GO
--------
CREATE  PROCEDURE ELIMFARMACEUTICO
@VAR VARCHAR(15)
AS
BEGIN
	DELETE 
	FROM [DESKTOP-CGC0VV9].BASEMARCO.DBO.FARMACEUTICO
	WHERE ID_FAR=@VAR 

	UPDATE [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA
	SET ID_FAR1=NULL
	WHERE ID_FAR1=@VAR

END   
GO
--------
CREATE  PROCEDURE ELIMFARMACIA
@VAR VARCHAR(15)
AS
BEGIN
	DELETE 
	FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA
	WHERE ID_FARMACIA=@VAR 

	UPDATE [USER-PC].BASEJORGE.DBO.FARMEDPREUN
	SET ID_FARMACIA2=NULL
	WHERE ID_FARMACIA2=@VAR

	UPDATE [DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO
	SET ID_FARMACIA4=NULL
	WHERE ID_FARMACIA4=@VAR
END   
GO
--------
CREATE  PROCEDURE ELIMMEDACC
@VAR VARCHAR(15), @VAR2 VARCHAR(15)
AS
BEGIN
	DELETE 
	FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDACC
	WHERE ID_MED3=@VAR AND ID_ACCT1=@VAR2 

END   

GO
--------
CREATE  PROCEDURE ELIMMEDMONO
@VAR VARCHAR(15), @VAR2 VARCHAR(15)
AS
BEGIN
	DELETE 
	FROM [LAPTOP-61QAQSQG].BASEKEVS.DBO.MEDMONO
	WHERE ID_MED2=@VAR AND ID_MONO1=@VAR2 

END   
GO

--------
CREATE  PROCEDURE ELIMFARMEDPREUN
@VAR VARCHAR(15), @VAR2 VARCHAR(15), @VAR3 VARCHAR(15), @VAR4 VARCHAR(15)
AS
BEGIN
	DELETE 
	FROM [USER-PC].BASEJORGE.DBO.FARMEDPREUN
	WHERE ID_FARMACIA2=@VAR AND ID_MED1=@VAR2 AND ID_PRES1=@VAR3 AND ID_UM1=@VAR4

END   
GO
--------
CREATE  PROCEDURE ELIMFARMTIPO
@VAR VARCHAR(15), @VAR2 VARCHAR(15)
AS
BEGIN
	DELETE  
	FROM [USER-PC].BASEJORGE.DBO.FARMTIPO
	WHERE ID_FARMACIA1=@VAR AND ID_TIPOTELF2= @VAR2
END   
GO

--------
CREATE  PROCEDURE ELIMEMPTIPO
@VAR VARCHAR(15), @VAR2 VARCHAR(15)
AS
BEGIN
	DELETE  
	FROM [DESKTOP-CJ3JHQ2].BASEULI.DBO.EMPTIPO
	WHERE ID_TIPOTELF1=@VAR AND ID_EMP1= @VAR2
END   


---------------------------------------------------------------------------------
------------------------------ PROCEDIMIENTOS ACTUALIZACIONES  ------------------
---------------------------------------------------------------------------------
---- COLONIA (KEVIN)
CREATE  PROCEDURE ACTCOLONIA
@VAR VARCHAR(15), @NOMC VARCHAR (50) 
AS 
BEGIN 
	IF ((EXISTS(SELECT * FROM [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA WHERE  @VAR=ID_COL)))
		BEGIN
			PRINT 'DATOS ACTUALIZADOS CORRECTAMENTE'
			UPDATE  [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA
				SET NOM_COL=UPPER( @NOMC)
			WHERE  ID_COL=@VAR
		END   
	 
	ELSE   
		BEGIN 
			PRINT 'ERROR, DATOS NO ACTUALIZADOS'
		END    
END   
GO
---- ALCALDIA (MAURICIO)

CREATE  PROCEDURE ACTALCALDIA
@VAR VARCHAR(15), @NOMC VARCHAR (50) 
AS 
BEGIN 
	IF ((EXISTS(SELECT * FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA WHERE  @VAR=ID_ALCA)))
		BEGIN
			PRINT 'DATOS ACTUALIZADOS CORRECTAMENTE'
			UPDATE  [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA
				SET NOM_ALCA=UPPER( @NOMC)
			WHERE  ID_ALCA=@VAR
		END   
	 
	ELSE   
		BEGIN 
			PRINT 'ERROR, DATOS NO ACTUALIZADOS'
		END    
END   
GO

---- ACCIONTERAP (GENARO)
CREATE  PROCEDURE ACTACCIONTERAP
@VAR VARCHAR(15), @NOMC VARCHAR (80) 
AS 
BEGIN 
	IF ((EXISTS(SELECT * FROM [DESKTOP-DG326LV].BASEGENARO.DBO.ACCIONTERAP WHERE  @VAR=ID_ACCT)))
		BEGIN
			PRINT 'DATOS ACTUALIZADOS CORRECTAMENTE'
			UPDATE  [DESKTOP-DG326LV].BASEGENARO.DBO.ACCIONTERAP
				SET NOM_ACCT=UPPER( @NOMC)
			WHERE  ID_ACCT=@VAR
		END   
	 
	ELSE   
		BEGIN 
			PRINT 'ERROR, DATOS NO ACTUALIZADOS'
		END    
END   
GO

---- MONODROGA (YAIR)
CREATE  PROCEDURE ACTMONODROGA
@VAR VARCHAR(15), @NOMC VARCHAR (100) 
AS 
BEGIN 
	IF ((EXISTS(SELECT * FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.MONODROGA WHERE  @VAR=ID_MONO)))
		BEGIN
			PRINT 'DATOS ACTUALIZADOS CORRECTAMENTE'
			UPDATE  [LAPTOP-IM7I95NH].BASEYAIR.DBO.MONODROGA
				SET NOM_MONO=UPPER( @NOMC)
			WHERE  ID_MONO=@VAR
		END   
	 
	ELSE   
		BEGIN 
			PRINT 'ERROR, DATOS NO ACTUALIZADOS'
		END    
END   
GO

---- LABORATORIO (GENARO)
CREATE  PROCEDURE ACTLABORATORIO
@VAR VARCHAR(15), @NOMC VARCHAR (100) 
AS 
BEGIN 
	IF ((EXISTS(SELECT * FROM [DESKTOP-DG326LV].BASEGENARO.DBO.LABORATORIO WHERE  @VAR=ID_LAB)))
		BEGIN
			PRINT 'DATOS ACTUALIZADOS CORRECTAMENTE'
			UPDATE  [DESKTOP-DG326LV].BASEGENARO.DBO.LABORATORIO
				SET NOM_LAB=UPPER( @NOMC)
			WHERE ID_LAB=@VAR
		END   
	 
	ELSE   
		BEGIN 
			PRINT 'ERROR, DATOS NO ACTUALIZADOS'
		END    
END   
GO
---- UNIDADMEDIDA (YAIR)
CREATE  PROCEDURE ACTUNIDADMEDIDA
@VAR VARCHAR(15), @NOMC VARCHAR (100) 
AS 
BEGIN 
	IF ((EXISTS(SELECT * FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.UNIDADMEDIDA WHERE  @VAR=ID_UM)))
		BEGIN
			PRINT 'DATOS ACTUALIZADOS CORRECTAMENTE'
			UPDATE  [LAPTOP-IM7I95NH].BASEYAIR.DBO.UNIDADMEDIDA
				SET CANT_UM =UPPER( @NOMC)
			WHERE ID_UM=@VAR
		END   
	 
	ELSE   
		BEGIN 
			PRINT 'ERROR, DATOS NO ACTUALIZADOS'
		END    
END   
GO
---- PRESENTACION (BRIAN)
CREATE  PROCEDURE ACTPRESENTACION 
@VAR VARCHAR(15), @NOMC VARCHAR (50) 
AS 
BEGIN 
	IF ((EXISTS(SELECT * FROM [DESKTOP-IUOOUHP].BASEBRIAN.DBO.PRESENTACION WHERE  @VAR=id_pres)))
		BEGIN
			PRINT 'DATOS ACTUALIZADOS CORRECTAMENTE'
			UPDATE [DESKTOP-IUOOUHP].BASEBRIAN.DBO.PRESENTACION
				SET TIPO_PRES =UPPER( @NOMC)
			WHERE id_pres=@VAR
		END   
	 
	ELSE   
		BEGIN 
			PRINT 'ERROR, DATOS NO ACTUALIZADOS'
		END    
END   
GO

---- PUESTO (MARCO)
CREATE  PROCEDURE ACTPUESTO
@VAR VARCHAR(15), @NOMC VARCHAR (50) 
AS 
BEGIN 
	IF ((EXISTS(SELECT * FROM [DESKTOP-CGC0VV9].BASEMARCO.DBO.PUESTO WHERE  @VAR=ID_PUESTO)))
		BEGIN
			PRINT 'DATOS ACTUALIZADOS CORRECTAMENTE'
			UPDATE [DESKTOP-CGC0VV9].BASEMARCO.DBO.PUESTO
				SET NOM_PUESTO =UPPER( @NOMC)
			WHERE ID_puesto=@VAR
		END   
	 
	ELSE   
		BEGIN 
			PRINT 'ERROR, DATOS NO ACTUALIZADOS'
		END    
END   
GO
---- TIPOTELF (GENARO)
CREATE  PROCEDURE ACTTIPOTELF
@VAR VARCHAR(15), @NOMC VARCHAR (50) 
AS 
BEGIN 
	IF ((EXISTS(SELECT * FROM [DESKTOP-DG326LV].BASEGENARO.DBO.TIPOTELF WHERE  @VAR=ID_TIPOTELF)))
		BEGIN
			PRINT 'DATOS ACTUALIZADOS CORRECTAMENTE'
			UPDATE [DESKTOP-DG326LV].BASEGENARO.DBO.TIPOTELF
				SET NOM_TIPOTELF =UPPER( @NOMC)
			WHERE ID_TIPOTELF=@VAR
		END   
	 
	ELSE   
		BEGIN 
			PRINT 'ERROR, DATOS NO ACTUALIZADOS'
		END    
END   
GO
---- CIUDAD (KEVIN)
CREATE  PROCEDURE ACTCIUDAD
@VAR VARCHAR(15), @NOMC VARCHAR (50) 
AS 
BEGIN 
	IF ((EXISTS(SELECT * FROM [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD WHERE  @VAR=ID_CIU)))
		BEGIN
			PRINT 'DATOS ACTUALIZADOS CORRECTAMENTE'
			UPDATE [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD
				SET NOM_CIU =UPPER( @NOMC)
			WHERE ID_CIU=@VAR
		END   
	 
	ELSE   
		BEGIN 
			PRINT 'ERROR, DATOS NO ACTUALIZADOS'
		END    
END   
GO
---- HORARIO (ULISES)
CREATE  PROCEDURE ACTHORARIO
@VAR VARCHAR(15), @NOMC VARCHAR (50) 
AS 
BEGIN 
	IF ((EXISTS(SELECT * FROM [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO WHERE  @VAR=ID_HOR)))
		BEGIN
			PRINT 'DATOS ACTUALIZADOS CORRECTAMENTE'
			UPDATE [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO
				SET TURNO =UPPER( @NOMC)
			WHERE ID_HOR=@VAR
		END   
	 
	ELSE   
		BEGIN 
			PRINT 'ERROR, DATOS NO ACTUALIZADOS'
		END    
END   
GO
---- CALLE (ULISES)
CREATE  PROCEDURE ACTCALLE
@VAR VARCHAR(15), @NOMC VARCHAR (50) 
AS 
BEGIN 
	IF ((EXISTS(SELECT * FROM [DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE WHERE  @VAR=ID_CALLE)))
		BEGIN
			PRINT 'DATOS ACTUALIZADOS CORRECTAMENTE'
			UPDATE [DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE
				SET NOM_CALLE =UPPER( @NOMC)
			WHERE ID_CALLE=@VAR
		END   
	 
	ELSE   
		BEGIN 
			PRINT 'ERROR, DATOS NO ACTUALIZADOS'
		END    
END   
GO

---- MEDICAMENTO (MAURICIO)
CREATE PROCEDURE ACTMEDICAMENTO
	@IDM VARCHAR(15), @NM VARCHAR(50), @IDL VARCHAR(15)
	AS 
	BEGIN
	IF ((NOT EXISTS(SELECT * FROM [DESKTOP-DG326LV].BASEGENARO.DBO.LABORATORIO WHERE  @IDL=ID_LAB)))
	 BEGIN
	 PRINT 'CLAVES FORANEAS NO ENCONTRADAS'
	END   

	ELSE   
		BEGIN 
		PRINT 'DATOS ACTUALIZADOS CORRECTAMENTE'
		UPDATE [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO
			SET NOM_MED=UPPER( @NM) , ID_LAB1=UPPER(@IDL)
		WHERE  ID_MED=@IDM
	END   
END   
GO

---- EMPLEADO (BRIAN)
CREATE PROCEDURE ACTEMPLEADO
	@IDF VARCHAR(15), @AP VARCHAR(50), @AM VARCHAR(50), @NOM VARCHAR(50),  
	@ND INT, @CP INT, @F DATE,  
	@IDCA1 VARCHAR(15), @IDCOL1 VARCHAR(15),@IDAL1 VARCHAR(15),@IDCIU1 VARCHAR(15),
	@IDPUE1 VARCHAR(15),@IDHOR1 VARCHAR(15), @IDFAR4 VARCHAR(15)
	AS 
	BEGIN
	IF ((NOT EXISTS(SELECT * FROM[DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE WHERE  @IDCA1=ID_CALLE))  OR
		(NOT EXISTS(SELECT * FROM [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA WHERE @IDCOL1=ID_COL)) OR
		(NOT EXISTS(SELECT * FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA WHERE  @IDAL1=ID_ALCA)) OR 
		(NOT EXISTS(SELECT *  FROM [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD WHERE @IDCIU1=ID_CIU)) OR 
		(NOT EXISTS(SELECT *  FROM [DESKTOP-CGC0VV9].BASEMARCO.DBO.PUESTO WHERE @IDPUE1=ID_PUESTO)) OR
		(NOT EXISTS(SELECT * FROM [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO WHERE  @IDHOR1=ID_HOR)) OR
		(NOT EXISTS(SELECT *  FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA WHERE @IDFAR4=ID_FARMACIA)))
	 BEGIN
	 PRINT 'CLAVES FORANEAS NO ENCONTRADAS'
	END   

	ELSE   
		BEGIN 
		PRINT 'DATOS ACTUALIZADOS CORRECTAMENTE'
		UPDATE [DESKTOP-IUOOUHP].BASEBRIAN.DBO.EMPLEADO
			SET APAT_EMP=UPPER( @AP) , AMAT_EMP=UPPER(@AM) , NOM_EMP=UPPER(@NOM), 
			NEXT_EMP=@ND , CP_EMP=@CP, FNAC_EMP=@F,
			ID_CALLE1=UPPER(@IDCA1) , ID_COL1=UPPER(@IDCOL1), 
			ID_ALCA1=UPPER(@IDAL1), ID_CIU1=UPPER(@IDCIU1),ID_PUESTO1=UPPER(@IDPUE1), ID_HOR1=UPPER(@IDHOR1),
			ID_FARMACIA4=UPPER(@IDFAR4)
		WHERE  ID_EMP=@IDF
	END   
END   
GO

---- FARMACEUTICO (MARCO)
CREATE PROCEDURE ACTFARMACEUTICO
	@IDF VARCHAR(15), @AP VARCHAR(20), @AM VARCHAR(20), @NOM VARCHAR(30),  
	@ND INT, @CP INT, @CED INT,@CORREO VARCHAR(25), @IDC VARCHAR(15), 
	@IDCOL VARCHAR(15), @IDDEL VARCHAR(15),@IDCD VARCHAR(15),@IDH VARCHAR(15)
	AS 
	BEGIN
	IF ((NOT EXISTS(SELECT * FROM[DESKTOP-CJ3JHQ2].BASEULI.DBO.CALLE WHERE  @IDC=ID_CALLE))  OR
		(NOT EXISTS(SELECT * FROM [LAPTOP-61QAQSQG].BASEKEVS.DBO.COLONIA WHERE @IDCOL=ID_COL)) OR
		(NOT EXISTS(SELECT * FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.ALCALDIA WHERE  @IDDEL=ID_ALCA)) OR 
		(NOT EXISTS(SELECT *  FROM [LAPTOP-61QAQSQG].BASEKEVS.DBO.CIUDAD WHERE @IDCD=ID_CIU)) OR 
		(NOT EXISTS(SELECT * FROM [DESKTOP-CJ3JHQ2].BASEULI.DBO.HORARIO WHERE  @IDH=ID_HOR)))
	 BEGIN
	 PRINT 'CLAVES FORANEAS NO ENCONTRADAS'
	END   

	ELSE   
		BEGIN 
		PRINT 'DATOS ACTUALIZADOS CORRECTAMENTE'
		UPDATE  [DESKTOP-CGC0VV9].BASEMARCO.DBO.FARMACEUTICO
			SET APAT_FAR=UPPER( @AP) , AMAT_FAR=UPPER(@AM) , NOM_FAR=UPPER(@NOM), 
			NEXT_FAR=@ND , CP_FAR=@CP, CEDULA_FAR=UPPER(@CED), 
			CORREO_FAR=UPPER(@CORREO), ID_CALLE2=UPPER(@IDC) , ID_COL2=UPPER(@IDCOL), 
			ID_ALCA2=UPPER(@IDDEL), ID_CIU2=UPPER(@IDCD), ID_HOR2=UPPER(@IDH)
		WHERE  ID_FAR=@IDF
	END   
END   
GO

---- FARMACIA (YAIR)
CREATE PROCEDURE ACTFARMACIA
	@IDM VARCHAR(15), @NM VARCHAR(100), @DIR VARCHAR(150),  @IDFA VARCHAR(15)
	AS 
	BEGIN
	IF ((NOT EXISTS(SELECT * FROM [DESKTOP-CGC0VV9].BASEMARCO.DBO.FARMACEUTICO WHERE  @IDFA=ID_FAR)))
	 BEGIN
	 PRINT 'CLAVES FORANEAS NO ENCONTRADAS'
	END   

	ELSE   
		BEGIN 
		PRINT 'DATOS ACTUALIZADOS CORRECTAMENTE'
		UPDATE [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA
			SET NOM_FARMACIA=UPPER( @NM) , DIREC_FARMACIA=UPPER(@DIR), ID_FAR1=UPPER(@IDFA)
		WHERE  ID_FARMACIA=@IDM
	END   
END   
GO

---- MEDACC (MAURICIO) ------ NO LLEVA ACTUALIZACION

---- MEDMONO (KEVIN) ------ NO LLEVA ACTUALIZACION

---- FARMEDPREUN (JORGE)
CREATE PROCEDURE ACTFARMEDPREUN
	@FOL VARCHAR(10), @IDF2 VARCHAR(15), @IDM1 VARCHAR(15), @IDP1 VARCHAR(15),  @IDUM1 VARCHAR(15),
	 @PREC SMALLINT, @STOCK SMALLINT
	AS 
	BEGIN
	IF ((NOT EXISTS(SELECT * FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.FARMACIA WHERE  @IDF2=ID_FARMACIA))OR
		(NOT EXISTS(SELECT * FROM [DESKTOP-JQTOAGH].BASEMAU.DBO.MEDICAMENTO WHERE  @IDM1=ID_MED))OR
		(NOT EXISTS(SELECT * FROM [DESKTOP-IUOOUHP].BASEBRIAN.DBO.PRESENTACION WHERE  @IDP1=ID_PRES))OR
		(NOT EXISTS(SELECT * FROM [LAPTOP-IM7I95NH].BASEYAIR.DBO.UNIDADMEDIDA WHERE  @IDUM1=ID_UM)))
	 BEGIN
	 PRINT 'CLAVES FORANEAS NO ENCONTRADAS'
	END   

	ELSE   
		BEGIN 
		PRINT 'DATOS ACTUALIZADOS CORRECTAMENTE'
		UPDATE [USER-PC].BASEJORGE.DBO.FARMEDPREUN
			SET ID_FARMACIA2=UPPER( @IDF2) , ID_MED1=UPPER(@IDM1), ID_PRES1=UPPER(@IDP1), ID_UM1=UPPER(@IDUM1) , PRECIO=(@PREC), STOCK=(@STOCK)
		WHERE  FOLIO=@FOL
	END   
END   
GO
---- FARMTIPO (JORGE)
CREATE PROCEDURE ACTFARMTIPO
	@IDF1 VARCHAR(15), @IDTT2 VARCHAR(15), @NT VARCHAR(12)
	AS 
		BEGIN 
		PRINT 'DATOS ACTUALIZADOS CORRECTAMENTE'
		UPDATE [USER-PC].BASEJORGE.DBO.FARMTIPO
			SET TELEFONO2=UPPER( @NT)
		WHERE  ID_FARMACIA1=@IDF1 AND ID_TIPOTELF2=@IDTT2
	END   
	GO

---- EMPTIPO (ULISES)
CREATE PROCEDURE ACTEMPTIPO
	@IDEP1 VARCHAR(15), @IDTT1 VARCHAR(15), @NT1 VARCHAR(12)
	AS 
		BEGIN 
		PRINT 'DATOS ACTUALIZADOS CORRECTAMENTE'
		UPDATE [DESKTOP-CJ3JHQ2].BASEULI.DBO.EMPTIPO
			SET TELEFONO1=UPPER( @NT1)
		WHERE  ID_EMP1=@IDEP1 AND ID_TIPOTELF1=@IDTT1
	END   
	/*
------------------------ ULTIMA ENTREGA(Por si quieren hacer pruebas la sintaxis es la de abajo ) ------------------------
							╮（╯◇╰）╭

---- CONSULTAS SIMPLES
EXEC CONSCOLONIA
EXEC CONSALCALDIA
EXEC CONSACCIONTERAP
EXEC CONSMONODROGA
EXEC CONSLABORATORIO
EXEC CONSUNIDADMEDIDA
EXEC CONSPRESENTACION
EXEC CONSPUESTO
EXEC CONSTIPOTELF
EXEC CONSCIUDAD
EXEC CONSHORARIO
EXEC CONSCALLE
EXEC CONSMEDICAMENTO
EXEC CONSEMPLEADO
EXEC CONSFARMACEUTICO
EXEC CONSFARMACIA
EXEC CONSMEDACC
EXEC CONSMEDMONO
EXEC CONSFARMEDPREUN
EXEC CONSFARMTIPO
EXEC CONSEMPTIPO


---- CONSULTAS COMPLEJAS
EXEC CONFD
EXEC CONC2
EXEC CONC3
EXEC CONC4
EXEC CONC5
EXEC CONC6
EXEC CONC7
EXEC CONC8

------ BUSQUEDAS COMPLEJAS
EXEC BUS11 '2'
EXEC BUS12 'NANCY'
EXEC BUS13 'matutino'

EXEC BUS21 '1'
EXEC BUS22 'HUGO'
EXEC BUS23 'Ingeniero ISC'
EXEC BUS24 'MATUTINO'

EXEC BUS31 'FARMACIA 1'
EXEC BUS32 'CELULAR'

EXEC BUS41 'BRIAN'
EXEC BUS42 'CASA'

EXEC BUS51 'VIRGINIA'
EXEC BUS52 'FARMACIA 4'

EXEC BUS61 'SALBUTAMOL'
EXEC BUS62 'TERAZOSINA'

EXEC BUS71 'ASPIRINA'
EXEC BUS72 'LABORATORIO SAN ANGEL'
EXEC BUS73 'ALIVIO PARA COLICOS'

EXEC BUS81 'AMLODIPINA'
EXEC BUS82 'Polvo'
EXEC BUS83 'FARMACIA 6'
EXEC BUS84 '2002'
EXEC BUS85 '234','PARACETAMOL'
EXEC BUS86 '55','LEXOTIROXINA'


---INSERCIONES 2: 
EXEC INGCOLONIA 'X', 'Colonia de Brian'
EXEC INGALCALDIA 'X', 'Alcaldia de Brian'
EXEC INGACCIONTERAP 'X','Brian el terapeutico'
EXEC INGMONODROGA 'X','Brian opio'
EXEC INGLABORATORIO 'X','Laboratorio de Brian'
EXEC INGUNIDADMEDIDA 'X','Brianes'
EXEC INGPRESENTACION 'X','Hola soy Brian'
EXEC INGPUESTO 'X','De tamales'
EXEC INGTIPOTELF 'X','Analogico lunar'
EXEC INGCIUDAD 'X','brianopolis'
EXEC INGHORARIO 'X','nocturno oscurito'
EXEC INGCALLE 'X','canal de don brian'
EXEC INGFARMACIA 'X','farmacia brian final','san se acabo','2'

EXEC INGMEDICAMENTO 'X','medicamento de brian final','LAB81XNZ44M4'
EXEC INGEMPLEADO 'X','marin','perez','brian trabajador',23,15278,'12-12-2002','CALL36BGI90P7','COLE30CNV55R4','ALCE90MEJ27U6','CIUD68FUX18I2','PUES95WEJ90F8','HOR76ZYB15P7','FARMA44HXI74S9'
EXEC INGFARMACEUTICO 'x','marin','cruz',' brian final',155,810,'9877985','brian@GMAIL.COM','CALL36BGI90P7','COLE17UTS43F4','ALCE90MEJ27U6','CIUD68FUX18I2','HOR76ZYB15P7'

EXEC INGMEDACC '1','1'
EXEC INGMEDMONO '2','3'
EXEC INGFARMEDPREUN '1','1','2','1','495','650','90'
EXEC INGFARMTIPO '1','1','55-1910-0002'
EXEC INGEMPTIPO '1','1', '55-1122-4245'


 ---ELIMINACIONES: 
EXEC ELIMCOLONIA 'COLE37KHZ98V5'
EXEC ELIMALCALDIA '8'
EXEC ELIMACCIONTERAP '8'
EXEC ELIMMONODROGA 'MOND81WSE81Y3'
EXEC ELIMLABORATORIO '9'
exec ELIMUNIDADMEDIDA '9'
EXEC ELIMPRESENTACION '9'
EXEC ELIMPUESTO 'P67DHH21J8'
EXEC ELIMTIPOTELF 'TTEL67SGN95R7'
EXEC ELIMCIUDAD '1' 
EXEC ELIMHORARIO '4'
EXEC ELIMCALLE1 'CALL14ZDY98U1'
EXEC ELIMMEDICAMENTO 'MED77TRY69J1'
EXEC ELIMEMPLEADO 'EMP24PHA78F5' 
EXEC ELIMFARMACEUTICO 'FAR93WDU72O8' 
EXEC CONSFARMACIA 'FARMA42DRU40E7'


--- ACTUALIZACIONES
EXEC ACTEMPLEADO '1'	,'ROSADO'	,'RUIZ'	,'BRIAN' ,'3'	,'198'	,'1982'	,'1990-10-19'	,'1'	,'1'	,'1'	,'1'	,'1'	,'1'	,'1'
EXEC ACTCOLONIA 'COLE21LGB71Q8', 'SAN AGUSTIN ACT'
EXEC ACTALCALDIA 'ALCE12JFG75E5', 'BRIAN FINAL 2'
EXEC ACTACCIONTERAP 'ACCT28CGS94C5', 'BRIAN ACCT FINAL'
EXEC ACTMONODROGA 'MOND17TYD84T3','BRIAN MONODROGA actualizado'
EXEC ACTLABORATORIO 'LAB21LNS90Y5', 'LABORATORIO ACTUALIZADO'
EXEC ACTUNIDADMEDIDA 'UDM35ANW69Q5', 'bri actualizado'
EXEC ACTPRESENTACION 'PRES26SIC89U8','oresentacion bri actualizado'
EXEC ACTPUESTO 'PUES46IKU39L6','puesto brian actu'
EXEC ACTTIPOTELF 'TTEL65HQV32I2', 'ESPACIAL ACTUALIZADO'
EXEC ACTCIUDAD 'CIUD55SPT64I6', 'Berlin actualizado'
EXEC ACTHORARIO 'HOR41RUU69T6','horario bri actu'
EXEC ACTCALLE 'CALL71BLY42Q7', 'calle actu'
EXEC ACTFARMEDPREUN '1','1','5','1','3',120,30
EXEC ACTFARMTIPO '5','10','55-8811-0022'
EXEC ACTMEDICAMENTO 'MED13SLN64Q1',	'MEDICAMENTO actu',	'1'
EXEC ACTEMPLEADO 'EMP22HUK28Y4',	'COLABORADOR'	,'YAIR'	,'JARAMAR actu'	,'20',	'6258',	'1992-02-02'	,'2'	,'1',	'4',	'9',	'1',	'2',	'8'
EXEC ACTFARMACEUTICO 'FAR86PHD34D2','rosado','ruiz','brian act','155','810','9877985','correo@GMAIL.COM','1','4','6','1','1'
EXEC ACTFARMACIA 'FARMA88IHB92U6','FARMACIA JORGE2','SAN JORGE2','1'
*/
select * from sysobjects where xtype='p'

